- hosts: app
  tasks:
    - name: create sources directory
      file:
        path: /src
        state: directory
        mode: 0755

    - name: copy sources
      copy:
        src: "{{ lookup('pipe', 'dirname `pwd`') }}/{{ item }}"
        dest: "/src/{{ item }}"
      with_items:
        - package.json
        - app.js

    - name: install app
      npm:
        production: yes
        path: /src
        state: latest
