#cloud-config
write_files:
  - path: /root/.docker/ca.pem
    content: ${ca_pem}
    permissions: '0400'
    encoding: b64

  - path: /root/.docker/cert.pem
    content: ${swarm_node_cert_pem}
    permissions: '0400'
    encoding: b64

  - path: /root/.docker/key.pem
    content: ${swarm_node_key_pem}
    permissions: '0400'
    encoding: b64

  - path: /etc/sysconfig/docker
    content: |
      OPTIONS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify"

runcmd:
  - yum update -y
  - curl -fsSL https://get.docker.com/ | sh
  - service docker start
  - usermod -aG docker ec2-user
  - export SWARM_VERSION=1.1.3
  - export EC2_PUBLIC_HOSTNAME=`curl http://169.254.169.254/latest/meta-data/public-hostname`
  - docker run -d swarm:$${SWARM_VERSION} join --advertise=$${EC2_PUBLIC_HOSTNAME}:2376 consul://${consul_ip}:8500
