#cloud-config
write_files:
  - path: /root/.docker/ca.pem
    content: ${ca_pem}
    permissions: '0400'
    encoding: b64

  - path: /root/.docker/cert.pem
    content: ${swarm_manager_cert_pem}
    permissions: '0400'
    encoding: b64

  - path: /root/.docker/key.pem
    content: ${swarm_manager_key_pem}
    permissions: '0400'
    encoding: b64

  - path: /etc/sysconfig/docker
    content: |
      OPTIONS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify"

runcmd:
  - yum update -y
  - curl -fsSL https://get.docker.com/ | sh
  - service docker start
  - export SWARM_VERSION=1.1.3
  - export EC2_PRIVATE_IPV4=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
  - export EC2_PUBLIC_HOSTNAME=`curl http://169.254.169.254/latest/meta-data/public-hostname`
  - docker run -d -p 3376:3376 -v /root/.docker:/root/.docker:ro --restart=always swarm:$${SWARM_VERSION} manage --replication --advertise=$${EC2_PUBLIC_HOSTNAME}:3376 --tlsverify --tlscacert=/root/.docker/ca.pem --tlscert=/root/.docker/cert.pem --tlskey=/root/.docker/key.pem --host=0.0.0.0:3376 consul://${consul_ip}:8500
