version: "2"
services:
  app:
    build:
      context: .
    image: tripler-tracker:docker-compose
    ports:
      - "80:80"
      - "443:443"
    command: ["node", "/src/app.js"]
    links:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
